[toolchain]
channel = "stable"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/dev-wallet1.json"

[programs.localnet]
escrow = "8uBMA8S33eGFMRA677Y1gPvmnBGUjFtdwxf2A8JufpA3"

[programs.devnet]
escrow = "8uBMA8S33eGFMRA677Y1gPvmnBGUjFtdwxf2A8JufpA3"
