[toolchain]
channel = "stable"
targets = ["bpf"]

[dependencies]
anchor-lang = "0.29.0"
anchor-spl = "0.29.0"

[features]
default = []
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["default/no-entrypoint"]
